name: Run Cucumber Tests and Send Report

on:
  push:
    branches: [ Automate1 ]
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Give permission to chromedriver (if used)
        run: chmod +x ./Xalts_Project/chromedriver.exe

      - name: Run Tests
        run: mvn clean test

      - name: Archive Test Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: test-output/ExtentReport.html
